// <auto-generated />
namespace PickemApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddForeignKeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddForeignKeys));
        
        string IMigrationMetadata.Id
        {
            get { return "201209172326226_AddForeignKeys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
