// <auto-generated />
namespace PickemApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_vwWeeklyPlayerPicks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_vwWeeklyPlayerPicks));
        
        string IMigrationMetadata.Id
        {
            get { return "201510010650095_Add_vwWeeklyPlayerPicks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
